# Generated by Django 5.0.7 on 2024-08-07 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=20)),
                ('point', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 7, 8, 55, 47, 746634))),
            ],
        ),
    ]
