# Generated by Django 5.0.7 on 2024-08-09 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_person_alter_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='nothing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 8, 41, 7, 660239)),
        ),
    ]
