# Generated by Django 5.0.7 on 2024-08-09 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 16, 54, 318232)),
        ),
    ]
