# Generated by Django 5.0.7 on 2024-08-09 08:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 8, 54, 23, 600478))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=6)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 8, 9, 8, 54, 23, 600725))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleforum.post')),
            ],
        ),
    ]
