# Generated by Django 5.0.7 on 2024-08-09 09:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleforum', '0002_alter_comment_date_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 40, 4, 377853)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='simpleforum.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 40, 4, 377590)),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.DecimalField(decimal_places=10, default=0.0, max_digits=1000000000)),
                ('usdt', models.DecimalField(decimal_places=10, default=100.0, max_digits=100000000)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='wallet', to='simpleforum.person')),
            ],
        ),
    ]
