# Generated by Django 4.2.7 on 2024-08-28 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_post_date_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 8, 36, 46, 13858)),
        ),
    ]
